language: rust

matrix:
  include:
    # - env: TARGET=x86_64-unknown-linux-gnu

    # - env: TARGET=thumbv6m-none-eabi
    #   if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    # - env: TARGET=thumbv7m-none-eabi
    #   if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    # NOTE used to build docs on successful merges to master
    - env: TARGET=x86_64-unknown-linux-gnu
      # FIXME revert this -- compiletest-rs v0.3.25 is broken with recent nightly
      rust: nightly-2019-10-31

    - env: TARGET=thumbv6m-none-eabi
      rust: nightly
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7m-none-eabi
      rust: nightly
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

before_install:
  - set -e
  - sudo apt-get update
  - sudo apt-get install -y binutils-arm-none-eabi

install:
  - bash ci/install.sh
  - export PATH="$PATH:$PWD/qemu"

script:
  - bash ci/script.sh

after_script: set +e

after_success:
  - bash ci/after-success.sh

cache: cache

before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
